services:
  postgres:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: go-api
    ports:
      - "3455:3455"
    env_file:
      - .env
    depends_on:
      - postgres

  nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile.nginx
    container_name: nginx-web
    ports:
      - "80:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro
    depends_on:
      - api

volumes:
  postgres_data: